defaults:
  - robot: flexiv
  - camera: realsense
  - marker: chessboard
  - calibration: eye_to_hand
  - collector: default
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
